//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditEventsFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditEventsFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.AuditEventsFile", typeof(AuditEventsFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} failed to authenticated. Date and Time: {1}.
        /// </summary>
        internal static string UserAuthenticationFailed {
            get {
                return ResourceManager.GetString("UserAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully authenticated. Date and Time: {1}.
        /// </summary>
        internal static string UserAuthenticationSuccess {
            get {
                return ResourceManager.GetString("UserAuthenticationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} changed passwords successfully. Date and Time: {1}.
        /// </summary>
        internal static string UserChangePasswordSuccess {
            get {
                return ResourceManager.GetString("UserChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} gained access to {1}&apos;s informations. Date and Time: {2}
        ///.
        /// </summary>
        internal static string UserDataAccess {
            get {
                return ResourceManager.GetString("UserDataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} gained access to {1} options. Date and Time: {2}.
        /// </summary>
        internal static string UserGroupAccess {
            get {
                return ResourceManager.GetString("UserGroupAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} failed to add group {1} because that group already exits. Date and Time: {2}.
        /// </summary>
        internal static string UserGroupAddFailed {
            get {
                return ResourceManager.GetString("UserGroupAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully added group {1}. Date and Time: {2}.
        /// </summary>
        internal static string UserGroupAddSuccess {
            get {
                return ResourceManager.GetString("UserGroupAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} succesfully deleted {1}. Date and time: {2}.
        /// </summary>
        internal static string UserGroupDeleteSuccess {
            get {
                return ResourceManager.GetString("UserGroupDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} failed to changed {1} name because that group already exits. Date and Time: {2}.
        /// </summary>
        internal static string UserGroupEditFailed {
            get {
                return ResourceManager.GetString("UserGroupEditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully changed {1} name to {2}. Date and Time: {3}.
        /// </summary>
        internal static string UserGroupEditSuccess {
            get {
                return ResourceManager.GetString("UserGroupEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully registrated on system. Date and Time: {1}.
        /// </summary>
        internal static string UserRegistrationSuccess {
            get {
                return ResourceManager.GetString("UserRegistrationSuccess", resourceCulture);
            }
        }
    }
}
